import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { HydratedDocument, Types } from 'mongoose';

export enum BoardType {
  CBSE = 'CBSE',
  ICSE = 'ICSE',
  STATE = 'STATE',
  IB = 'IB',
}

export type SchoolDocument = HydratedDocument<School>;

@Schema({ timestamps: true })
export class School {
  // `_id` is auto-generated by MongoDB/Mongoose.

  @Prop({ unique: true })
  schoolCode!: string;

  @Prop()
  schoolName!: string;

  @Prop()
  logo!: string;

  @Prop({ unique: true })
  email!: string;

  @Prop()
  phone!: string;

  @Prop()
  addressLine1!: string;

  @Prop()
  addressLine2!: string;

  @Prop()
  city!: string;

  @Prop()
  state!: string;

  @Prop()
  country!: string;

  @Prop()
  pincode!: string;

  @Prop({ enum: BoardType })
  boardType!: BoardType;

  @Prop()
  principalName!: string;

  @Prop()
  website!: string;

  @Prop()
  timezone!: string;

  @Prop()
  currency!: string;

  @Prop()
  academicYear!: string;

  @Prop()
  subscriptionPlan!: string;

  @Prop()
  subscriptionStartDate!: Date;

  @Prop()
  subscriptionEndDate!: Date;

  @Prop({ default: true })
  isActive!: boolean;

  @Prop({ type: Types.ObjectId, ref: 'User' })
  createdBy!: Types.ObjectId;
}

export const SchoolSchema = SchemaFactory.createForClass(School);
