import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { HydratedDocument, Types } from 'mongoose';

export enum TeacherStatus {
  ACTIVE = 'active',
  INACTIVE = 'inactive',
  RESIGNED = 'resigned',
}

export type TeacherDocument = HydratedDocument<Teacher>;

@Schema({ timestamps: true })
export class Teacher {
  // `_id` is auto-generated by MongoDB/Mongoose.

  @Prop()
  schoolId!: string;

  @Prop({ type: Types.ObjectId, ref: 'User' })
  userId!: Types.ObjectId;

  @Prop({ unique: true })
  employeeCode!: string;

  @Prop()
  firstName!: string;

  @Prop()
  lastName!: string;

  @Prop()
  fullName!: string;

  @Prop()
  gender!: string;

  @Prop()
  dob!: Date;

  @Prop()
  phone!: string;

  @Prop()
  email!: string;

  @Prop()
  qualification!: string;

  @Prop()
  specialization!: string;

  @Prop()
  experienceYears!: number;

  @Prop()
  joiningDate!: Date;

  @Prop({ type: [String], default: [] })
  subjects!: string[];

  @Prop({ type: Types.ObjectId, ref: 'Class' })
  classTeacherOf!: Types.ObjectId;

  @Prop()
  address!: string;

  @Prop()
  emergencyContact!: string;

  @Prop()
  profileImage!: string;

  @Prop({ enum: TeacherStatus, default: TeacherStatus.ACTIVE })
  status!: TeacherStatus;

  @Prop({ type: Types.ObjectId, ref: 'User' })
  createdBy!: Types.ObjectId;
}

export const TeacherSchema = SchemaFactory.createForClass(Teacher);
